" Vimrc
" Author: jiaobuzuji@163.com
" Github: https://github.com/jiaobuzuji
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set nocompatible
let $VIMFILES=fnamemodify(expand('<sfile>'), ":p:h")
set backspace=indent,eol,start
set history=200		" keep 200 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set wildmenu		" display completion matches in a status line

set ttimeout		" time out for key codes
set ttimeoutlen=100	" wait up to 100ms after Esc for special key

" Show a few lines of context around the cursor.  Note that this makes the
" text scroll if you mouse-click near the start or end of the window.
set scrolloff=5

set incsearch
set guioptions-=t
set nolangremap


" Don't use Ex mode, use Q for formatting.
" Revert with ":unmap Q".
map Q gq

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
" Revert with ":iunmap <C-U>".
inoremap <C-U> <C-G>u<C-U>

" In many terminal emulators the mouse works just fine.  By enabling it you
" can position the cursor, Visually select and scroll with the mouse.
" Only xterm can grab the mouse events when using the shift key, for other
" terminals use ":", select text and press Esc.
  set mouse=a

" Put these in an autocmd group, so that you can revert them with:
" ":augroup vimStartup | au! | augroup END"
augroup vimStartup
  au!

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid, when inside an event handler
  " (happens when dropping a file on gvim) and for a commit message (it's
  " likely a different one than last time).
  autocmd BufReadPost *
        \ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
        \ |   exe "normal! g`\""
        \ | endif

augroup END

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
" Revert with: ":delcommand DiffOrig".
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
        \ | wincmd p | diffthis
endif

" Options
se nowrap hls rnu ic scs cf
se sw=2 ts=2 sts=2 et sta sr si ci

" leader key
let g:mapleader="\<Space>"
let g:maplocalleader=','

inoremap j<space> j 
inoremap jj <esc>

inoremap v<space> v 
nnoremap vv	  :update<cr>
vnoremap vv	  <C-C>:update<cr>
inoremap vv	  <C-[>:update<cr>

nnoremap Y y$
nnoremap tt o<c-[>

nnoremap <leader>/ :nohlsearch<CR>

"visual mode hit tab forward indent ,hit shift-tab backward indent
"Reselect visual block after indent/outdent.
vnoremap <TAB>    >gv  
vnoremap <s-TAB>  <gv 
vnoremap <        <gv
vnoremap >        >gv

" Using <Plug> instead of
vnoremap  *  y/<C-R>=escape(@", '\\/.*$^~[]')<CR><CR>
vnoremap  #  y?<C-R>=escape(@", '\\/.*$^~[]')<CR><CR>

"replace
nnoremap ss :%s/<C-R>//
vnoremap ss :s/<C-R>//

" multiple windows and tabs {1
nnoremap <leader>qa :qa<cr>
nnoremap <leader>wd :q<cr>

" =======================================================
filetype plugin indent on
syntax on

set termguicolors " use GUI colors for the terminal
set background=dark   " "dark" or "light"; the background color brightness
colorscheme desert
" let g:jellybeans_use_term_italics = 1
" highlight Comment cterm=italic
" set t_ZH=[3m
" set t_ZR=[23m
